apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration-1-0
spec:
  ttlSecondsAfterFinished: 45
  template:
    spec:
      containers:
        - name:  database-migration-1-0
          image: docker-hub.private.com:5000/dbmigration:latest #change server name
          command: ["python",  "./dbmigration.py"]
          envFrom:
            - configMapRef:
                name: postgres-config
      restartPolicy: Never
      nodeSelector:
        nodetype: database
# run below command after jobs are completed
# kubectl get pods --no-headers=true |grep -v "Running" | grep -v "Pending" | sed -E 's/([a-z0-9-]+).*/\1/g' | xargs kubectl delete pod        